# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datefieldinput',
            old_name='parent_date_field',
            new_name='parent_field',
        ),
        migrations.RenameField(
            model_name='mcqfieldinput',
            old_name='parent_mcq_field',
            new_name='parent_field',
        ),
        migrations.RenameField(
            model_name='memofieldinput',
            old_name='parent_memo_field',
            new_name='parent_field',
        ),
        migrations.RenameField(
            model_name='numericfieldinput',
            old_name='parent_numeric_field',
            new_name='parent_field',
        ),
        migrations.RenameField(
            model_name='textfieldinput',
            old_name='parent_text_field',
            new_name='parent_field',
        ),
    ]
