# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=1000)),
                ('required', models.BooleanField(default=False)),
            ],
        ),
    ]
