# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(max_length=100)),
                ('body_text', models.CharField(max_length=1000)),
                ('deployed', models.BooleanField(default=False)),
            ],
        ),
    ]
