# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='form_name',
            field=models.CharField(default=b'New Form', max_length=100),
        ),
    ]
