# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0004_form_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='parent_form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='creator.Form'),
        ),
    ]
