# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0005_field_parent_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='sr_no',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
