# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0006_field_sr_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000)),
                ('sr_no', models.PositiveSmallIntegerField(default=0)),
                ('caption', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=1000)),
                ('required', models.BooleanField(default=False)),
                ('parent_form', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='creator.Form')),
            ],
        ),
    ]
