# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0007_textfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='parent_form',
        ),
        migrations.RemoveField(
            model_name='textfield',
            name='answer',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
    ]
