# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0008_auto_20170608_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.PositiveSmallIntegerField(default=0)),
                ('caption', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=1000)),
                ('required', models.BooleanField(default=False)),
                ('date_high', models.DateField()),
                ('date_low', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MCQField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.PositiveSmallIntegerField(default=0)),
                ('caption', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=1000)),
                ('required', models.BooleanField(default=False)),
                ('choices', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='MemoField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.PositiveSmallIntegerField(default=0)),
                ('caption', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=1000)),
                ('required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NumericField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.PositiveSmallIntegerField(default=0)),
                ('caption', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=1000)),
                ('required', models.BooleanField(default=False)),
                ('range_high', models.SmallIntegerField(default=0)),
                ('range_low', models.SmallIntegerField(default=-100)),
                ('decimal_places', models.SmallIntegerField(default=5)),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='numericfield',
            name='parent_form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='creator.Form'),
        ),
        migrations.AddField(
            model_name='memofield',
            name='parent_form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='creator.Form'),
        ),
        migrations.AddField(
            model_name='mcqfield',
            name='parent_form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='creator.Form'),
        ),
        migrations.AddField(
            model_name='datefield',
            name='parent_form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='creator.Form'),
        ),
    ]
